baseURL = "https://feditest.org"
title = "FediTest"
languageCode = "en-US"
defaultContentLanguage = "en"
disableKinds = [ "taxonomy" ]
enableRobotsTXT = true
enableGitInfo = true
theme = [ "fedidevs-hugo-theme" ]

[services.rss]
limit = 42

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[sitemap]
filename = "sitemap.xml"
